version: "3.3"

services:
  wrapper:
    build:
      context: image
      dockerfile: Dockerfile
    container_name: $CONTAINER_NAME
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    volumes:
      - $HOST_WORKSPACE_DIR:/workspace
    ports:
      - "127.0.0.1:3333:22"
